### ISSUE TITLE
No flashing e-paper display.

### ISSUE THREAD

**Issue by martinschultzkristensen** [arcbtc/1.21#4]
Hi,

Really great tutorial you have made. Thank you.

I cannot get the e-paper to flash, and I'm clueless now why.
I have tested that the jumpercable from 3v3 and GND is working correctly.
I have checked that the cables are placed correctly.
I also get the right "serial monitor" out when I monitor it:

20:43:26.467 -> rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
20:43:26.467 -> configsip: 0, SPIWP:0xee
20:43:26.467 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
20:43:26.467 -> mode:DIO, clock div:1
20:43:26.467 -> load:0x3fff0018,len:4
20:43:26.467 -> load:0x3fff001c,len:928
20:43:26.467 -> ho 0 tail 12 room 4
20:43:26.467 -> load:0x40078000,len:8424
20:43:26.467 -> ho 0 tail 12 room 4
20:43:26.467 -> load:0x40080400,len:5868
20:43:26.467 -> entry 0x4008069c
20:43:27.067 -> _PowerOn : 3
20:43:27.100 -> _Update_Full : 1001
20:43:27.172 -> _Update_Part : 1
20:43:27.209 -> _Update_Full : 1
20:43:27.276 -> ⸮connecting
20:43:27.547 -> connecting
20:43:27.652 -> connecting
20:43:27.754 -> connecting
20:43:27.855 -> connecting
20:43:27.957 -> connecting
20:43:28.058 -> connecting
20:43:28.166 -> connecting
20:43:28.268 -> connecting
20:43:28.374 -> connecting
20:43:28.442 -> connecting
20:43:28.542 -> connecting
20:43:28.645 -> connecting
20:43:28.756 -> connecting
20:43:28.860 -> connecting
20:43:28.969 -> connecting
20:43:29.069 -> connecting
20:43:29.171 -> connecting
20:43:29.273 -> connected
20:43:31.857 -> {"data":{"id":"7039828a-70d9-4b17-8e53-5f2abe7eee45","name":null,"description":"danceOmatic game","created_at":1567709010,"status":"unpaid","callback_url":null,"success_url":"https://opennode.co","order_id":"N/A","notes":"","currency":"BTC","source_fiat_value":0,"fiat_value":0.0417439242,"auto_settle":false,"notif_email":null,"lightning_invoice":{"expires_at":1567712610,"payreq":"LNBC4U1PWHZ46JPP5P6QZ9NPH3GPPHAR2KREQNAUVUEH6Q52VVU05GUQHR3K4ARHQEZGQDQ6V3SKUCM9FAKKZARFVVSXWCTDV5CQZPGZV37WEADN7R6SMR40F93WX85XZJAQRGHJ7CM0MUENK43H4T5V4UYACQN7CJ58XYNLRWVXY63ZQGSEPHC8ALZ02E36MT97DYRM5N5D4CQVAN6ZQ"},"chain_invoice":{"address":"3Mg2MrJBWwtv2atcbFXjeU4ffN2vHFVrpw"},"address":"3Mg2MrJBWwtv2atcbFXjeU4ffN2vHFVrpw","amount":400,"uri":"bitcoin:3Mg2MrJBWwtv2atcbFXjeU4ffN2vHFVrpw?amount=0.00000400&label=danceOmatic game&lightning=LNBC4U1PWHZ46JPP5P6QZ9NPH3GPPHAR2KREQNAUVUEH6Q52VVU05GUQHR3K4ARHQEZGQDQ6V3SKUCM9FAKKZARFVVSXWCTDV5CQZPGZV37WEADN7R6SMR40F93WX85XZJAQRGHJ7CM0MUENK43H4T5V4UYACQN7CJ58XYNLRWVXY63ZQGSEPHC8ALZ02E36MT97DYRM5N5D4CQVAN6ZQ"}}
20:43:31.928 -> LNBC4U1PWHZ46JPP5P6QZ9NPH3GPPHAR2KREQNAUVUEH6Q52VVU05GUQHR3K4ARHQEZGQDQ6V3SKUCM9FAKKZARFVVSXWCTDV5CQZPGZV37WEADN7R6SMR40F93WX85XZJAQRGHJ7CM0MUENK43H4T5V4UYACQN7CJ58XYNLRWVXY63ZQGSEPHC8ALZ02E36MT97DYRM5N5D4CQVAN6ZQ
20:43:33.919 -> _PowerOn : 3
20:43:33.955 -> _Update_Full : 1001
20:43:34.017 -> _PowerOff : 1

Do you have any advice, so I can get to the goal? 
Thanks!

**Comment by martinschultzkristensen** [comment]
Update:

I can pay the LN pay request, using the string from the serial monitor, and it returns paid. (So far so good). However nothing happens. I've tried to test around with the 3v jumpercable. 
**Do I have to do anything to activate the 3v GPIO?** Course it seems like it's not delivering any current.

**Comment by severedStrings** [comment]
Are you using a Black and White 1.54 inch E-Paper display? If you are using anything else you will need to adjust lines 4 and 10 of his example code to suit the type of display you are using. May not be the issue but even a slight change like using the display with red would require a change from GxEPD2_BW to GxEPD2_3C

**Comment by martinschultzkristensen** [comment]
Thanks for the response.
It is yes. [Here's a video i took of it](https://youtu.be/ik4hWhy9q9I)

So I run this code in the beginning:


`GxEPD2_BW<GxEPD2_154, GxEPD2_154::HEIGHT> display(GxEPD2_154(/*CS=5*/ SS, /*DC=*/ 22, /*RST=*/ 21, /*BUSY=*/ 4));`

**Comment by normandmickey** [comment]
Do you have an ESP32 or ESP32S?  The ESP32S is a clone and has a slightly
different pin configuration.

https://github.com/arcbtc/epaper-btc-price-fetcher/issues/1

**Comment by martinschultzkristensen** [comment]
I am positive it's a ESP32 (not the S-model)
It says on the back: ESP32 DEVKITV1

@ElectricTiger it is indeed an 1.54inch paper module display the MH-ET LIVE. I assume it's the black and white one, since the displayed screen, which it came with only showes black and white.

I'll try to run the BTC pricer-checker, and see if I run into the same problem.

**Comment by martinschultzkristensen** [comment]
Hey!
Just an update. I have tried to run the GxEPD & GxEPD_2 examples, to see if I could make those work. But also not. :(
I start to think my e-paper display is broken, course I'm sure it's wired up correctly.

**Comment by normandmickey** [comment]
That's a possibility.  When I built mine I bought two LCDs and the first
one I tried was DOA.

**Comment by martinschultzkristensen** [comment]
Yes curse I've really tried ALL the possibilities I can think of now. And Arduino's serial monitor gives me the correct output.
Do you know of any simple way to test for this, to get a definitive answer?
